# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: app-container
        image: melone30/express:latest
        ports:
        - containerPort: 4000
        envFrom:
          - configMapRef:
              name: app-config-map

